# travis-ci integration for the kiibohd controller firmware

sudo:
  - false

language:
  - c

os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - binutils-arm-none-eabi
      - gcc-arm-none-eabi
      - exuberant-ctags
        #- libc6-dev-i386 # Needed for clang!?
      - libnewlib-arm-none-eabi
      - tree

# Build Scripts
env:
  # Input Club Keyboard Tests
  - DIR=Keyboards SCRIPT=infinity.bash
  - DIR=Keyboards SCRIPT=infinity_led.bash
  - DIR=Keyboards SCRIPT=ergodox.bash
  - DIR=Keyboards SCRIPT=whitefox.bash

  # Debug Build Tests
  - DIR=Keyboards/Testing SCRIPT=uartout.bash
  - DIR=Keyboards/Testing SCRIPT=usbmuxuart.bash

  # Bootloader Build Tests
  - DIR=Bootloader/Builds SCRIPT=mk20dx128vlf5.bash
  - DIR=Bootloader/Builds SCRIPT=mk20dx256vlh7.bash

# Exclusions
matrix:
  # TODO - Still some travis clang issues
  allow_failures:
    - compiler: clang

  exclude:
    # Bootloader doesn't support clang yet
    - compiler: clang
      env: DIR=Bootloader/Builds SCRIPT=mk20dx128vlf5.bash
    - compiler: clang
      env: DIR=Bootloader/Builds SCRIPT=mk20dx256vlh7.bash

# System setup
install:
  # Info about OS
  - uname -a

  # Pre-clone kll.git to speed-up build
  - git clone https://github.com/kiibohd/kll.git

  # Directory tree to validate kll.git
  - tree

# Run test script(s)
script:
  - (cd ${DIR} && COMPILER=${CC} ./${SCRIPT})

# Post test script commands
after_script:
  - tree

